version: "3.1"
services:
  itoken-eureka-1:
    restart: always
    image: itoken-eureka
    container_name: itoken-eureka-1
    hostname: itoken-eureka-1
    ports:
      - 8761:8761
    networks:
      - bridge
    environment:
      - SPRING_PROFILES_ACTIVE=dev@1
      - HOST=172.28.7.46
  itoken-eureka-2:
    restart: always
    image: itoken-eureka
    container_name: itoken-eureka-2
    hostname: itoken-eureka-2
    ports:
      - 8861:8861
    networks:
      - bridge
    environment:
      - SPRING_PROFILES_ACTIVE=dev@2
      - HOST=172.28.7.46
  itoken-eureka-3:
    restart: always
    image: itoken-eureka
    container_name: itoken-eureka-3
    hostname: itoken-eureka-3
    ports:
      - 8961:8961
    networks:
      - bridge
    environment:
      - SPRING_PROFILES_ACTIVE=dev@3
      - HOST=172.28.7.46

networks:
  eureka-net:
    driver: bridge
